In [1]:
import numpy as np
x = np.array([3,4])
np.linalg.norm(x)

5.0

In [2]:
np.sqrt(np.dot(x,x))

5.0

In [3]:
x = np.array([3,4,5,6])
np.linalg.norm(x)

9.273618495495704

In [4]:
v = np.array([3,4])
u = v / np.linalg.norm(v)

In [5]:
np.linalg.norm(u)

1.0

In [6]:
v = np.array([3,4,5,6])
np.linalg.norm(v/np.linalg.norm(v))

0.9999999999999999

In [9]:
x = np.array([1,0])
y = np.array([0,1])
np.dot(x,y)

0

In [11]:
x1 = np.array([1,2,3])
x2 = np.array([0,3,1])
x3 = np.array([0,2,1])
y = 2*x1 + 1*x2 - 2*x3
print(y)

[2 3 5]


# 선형 종속

In [12]:
x1 = np.array([2,2,4])
x2 = np.array([2,2,3])
x3 = np.array([1,1,1])
y = 1*x1 - 2*x2 + 2*x3
print(y)

[0 0 0]


# 선형 독립

In [13]:
x1 = np.array([1,0,0])
x2 = np.array([0,1,0])
x3 = np.array([0,0,1])
y = 0*x1 + 0*x2 + 0*x3
print(y)
y2 = 0*x1 + 3*x2 + 0*x3
print(y2)

[0 0 0]
[0 3 0]


# 기저 벡터
기저 벡터는 선형 독립이어야만 존재 가능

In [14]:
A = np.array([[1,1,1],[2,2,2]])
A.shape

(2, 3)

In [15]:
B = np.array([[1,1,1,1,1], [2,2,2,2,2], [3,3,3,3,3]])
B.shape

(3, 5)

In [17]:
C = np.dot(A,B)
C

array([[ 6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12]])

In [18]:
A.shape, B.shape, C.shape

((2, 3), (3, 5), (2, 5))

In [20]:
np.eye(3) # 단위 벡터

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.trace(np.eye(4))

4.0

# 행렬식 (determinent)

In [22]:
A = np.array([[4,2],[1,3]])
A_det = np.linalg.det(A)     #  (4x3) - (2x1)
print(A, A_det)

[[4 2]
 [1 3]] 10.000000000000002
