# 1. 벡터 a = [1,9,3,7,5]의 크기를 구하시오

In [1]:
import numpy as np
a = np.array([1,9,3,7,5])
print(np.linalg.norm(a))

12.84523257866513


# 2. 벡터 b = [1,3,5]와 c = [2,4,6]의 내적을 구하시오.

In [2]:
b = [1,3,5]
c = [2,4,6]
np.dot(b,c)

44

# 3. 행렬 a = [1,2,3;4,5,6;7,8,9]의 트레이스, 행렬식, 역행렬, 고유치 및 그에 해당하는 고유벡터들을 구하시오. 그리고 b = a^T에 대한 값들도 구해보시오.

In [16]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a_tr = np.trace(a) # a의 트레이스
a_det = np.linalg.det(a) #a의 행렬식
# a_inv = np.linalg.inv(a)  a의 역행렬, 하지만 존재하지 않는다.
W, V = np.linalg.eig(a) # W : 고유치 , V : 고유 벡터

b = np.transpose(a) # b = a^T
b_tr = np.trace(b) # b의 트레이스
b_det = np.linalg.det(b) # b의 행렬식
# b_inv = np.linalg.inv(b)  b의 역행렬, 하지만 존재하지 않는다.
W_b, V_b = np.linalg.eig(b) # W_b : 고유치, V_b : 고유 벡터

print("Trace of a :", a_tr)
print("Determinant of a :", a_det)
# print("Inverse of a", a_inv)
print("eigenvalue of a :", W)
print("eigenvacter of a :", V)
print("="*20)
print("b :", b)
print("Trace of b :", b_tr)
print("Determinant of b :", b_det)
# print("Inverse of b", b_inv)
print("eigenvalue of b :", W_b)
print("eigenvacter of b :", V_b)



Trace of a : 15
Determinant of a : 0.0
eigenvalue of a : [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
eigenvacter of a : [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
b : [[1 4 7]
 [2 5 8]
 [3 6 9]]
Trace of b : 15
Determinant of b : 0.0
eigenvalue of b : [ 1.61168440e+01 -1.11684397e+00 -5.70069119e-16]
eigenvacter of b : [[-0.46454727 -0.88290596  0.40824829]
 [-0.57079553 -0.23952042 -0.81649658]
 [-0.67704379  0.40386512  0.40824829]]


# 4. 주어진 행렬 a = [1,0,0,0;,0,2,0,0';0,0,3,0;0,0,0,5] 의 트레이스, 행렬식, 역행렬, 고유치 및 그에 해당하는 고유벡터들을 구하시오.

In [21]:
a = np.array([[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,5]])
print("Trace of a : ", np.trace(a)) # a의 트레이스
print("Determinat of a \n: ", np.linalg.det(a)) # a의 행렬식
print("Inverse of a : \n", np.linalg.inv(a)) # a의 역행렬
W, V = np.linalg.eig(a)
print("eigenvalue of a : \n", W) # a의 고유치
print("eigenvecter of a : \n ", V) # a의 고유값

Trace of a :  11
Determinat of a 
:  29.99999999999999
Inverse of a : 
 [[1.         0.         0.         0.        ]
 [0.         0.5        0.         0.        ]
 [0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.2       ]]
eigenvalue of a : 
 [1. 2. 3. 5.]
eigenvecter of a : 
  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 5. 주어진 행렬 a = [1,2,3;2,1,2;3,2,1]의 트레이스, 행렬식, 고유치 및 그에 해당하는 고유벡터들을 구하시오.

In [24]:
a = np.array([[1,2,3],[2,1,2],[3,2,1]]) 
print("Trace of a : ", np.trace(a)) # a의 트레이스
print("Determinant of a  \n: ", np.linalg.det(a)) # a의 행렬식
W, V = np.linalg.eig(a)
print("eigenvalue of a : \n", W) # a의 고유치
print("eigenvector of a : \n", V) # a의 고유벡터

Trace of a :  3
Determinant of a  
:  8.000000000000002
eigenvalue of a : 
 [ 5.70156212 -2.         -0.70156212]
eigenvector of a : 
 [[-6.05912800e-01 -7.07106781e-01  3.64512933e-01]
 [-5.15499134e-01  1.47635207e-16 -8.56890100e-01]
 [-6.05912800e-01  7.07106781e-01  3.64512933e-01]]
