In [2]:
import numpy as np

a = np.array([1,2,3])
print(a, type(a))
print(a.shape)

print(a[0], a[1], a[2])

a[0] = 100
print(a)

b = np.array([[1,2,3], [4,5,6]])
print(b, b.shape)
print(b[0,0], b[1,1], b[0,2])

[1 2 3] <class 'numpy.ndarray'>
(3,)
1 2 3
[100   2   3]
[[1 2 3]
 [4 5 6]] (2, 3)
1 5 3


In [3]:
a = np.zeros((2,3))
print(a)
b = np.ones((4,3))
print(b)
c = np.full((2,2), 7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((3,4))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.5890195  0.32619389 0.35140241 0.88436947]
 [0.41662582 0.64995228 0.64860453 0.08271183]
 [0.34576622 0.31111237 0.79630455 0.47797234]]


In [4]:
a = np.arange(5)
print(a)
b = np.arange(1,3,0.4)
print(b)
c = np.linspace(1., 4., 5)
print(c)

[0 1 2 3 4]
[1.  1.4 1.8 2.2 2.6]
[1.   1.75 2.5  3.25 4.  ]


In [5]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
b = a[:2, 1:3]
print(b)
print(a[0,1])
b[0,0] = 77
print(b)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]
2
[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]]


In [6]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
row_1 = a[1, :]
row_2 = a[1:2, :]
print(row_1, row_1.shape)
print(row_2, row_2.shape)

col_1 = a[:, 1]



col_2 = a[:, 1:2]
print(col_1, col_1.shape)
print(col_2, col_2.shape)

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[2 6] (2,)
[[2]
 [6]] (2, 1)


In [7]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

row_r1 = a[1, :] # a의 두 번째 행 (정수 인덱싱)
row_r2 = a[1:2, :] # a의 두 번째 행 (슬라이싱)
print(row_1, row_1.shape) # 정수 인덱싱을 하면 차원이 하나 줄어듦(1차원 배열)
print(row_2, row_2.shape) # 행렬 형태 (2차원 행렬)
print("--*--" * 10)
col_r1 = a[:, 1] # a의 두번째 열 (정수 인덱싱)
col_r2 = a[:, 1:2] # a의 두번째 열 (슬라이싱)
print(col_r1, col_r1.shape) # a의 두 번째 열 (정수 인덱싱)
print(col_r2, col_r2.shape) # a의 두 번째 열 (슬라이싱)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
--*----*----*----*----*----*----*----*----*----*--
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [8]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a[[0,1,2], [0,1,0]]) # 특정한 element를 뽑기
print(np.array([a[0,0], a[1,1], a[2,0]])) # 특정한 element를 뽑아서 배열로 만들어줌
print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [9]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]]) # (4x3)배열
print(a)
b = np.array([0, 2, 0, 1]) # a의 특정한 element 4개를 뽑아낼 때 사용할 index 번호
print(b)
print(a[np.arange(4), b]) # a[0,0], a[1,2], a[2,0], a[3,1])를 뽑아내기

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[ 1  6  7 11]


In [10]:
# 부울 배열 인덱싱 : 배열 안에 부울 값만 넣고, 그 중에서 True 값만 뽑아내기
a = np.array([[1,2], [3,4], [5,6], [7,8]])
# 부울값으로 인덱스를 갖고 있는 배열
bool_idx = (a > 2) # a라는 배열에 2보다 큰 값들을 찾아서, 그 값들의 부울 값 (True of False)
print(bool_idx)
print(a[bool_idx]) # True인 값을 가지는 인덱스 위치의 값을 뽑아냄
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]
 [ True  True]]
[3 4 5 6 7 8]
[3 4 5 6 7 8]


In [11]:
import numpy as np

x = np.array([1,2])
print(x.dtype) # x가 갖고있는 값들의 datatype = 64bit 크기 정수

x = np.array([1.0, 2.0])
print(x.dtype) # x가 갖고 있는 datatype = 64bit 크기 실수

x = np.array([1,2], dtype= np.float64) # 직접 datatype 주기 : datatype를 np에서 제공되는 float64 type로 만듦
print(x.dtype)
print(x)

int32
float64
float64
[1. 2.]


In [13]:
x = np.array([[1,2], [3,4]], dtype= np.float64)
y = np.array([[5,6], [7,8]], dtype= np.float64)

print(x)
print(y)

print(x + y) # 해당 요소들끼리의 덧셈
print(np.add(x,y)) # x와 y를 더해준 값

print(x - y) # 해당 요소들끼리의 뺄셈
print(np.subtract(x,y)) # x와 y를 뺀 값

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [14]:
print(x * y) # 해당 요소들끼리의 곱셈
print(np.multiply(x, y)) # x와 y를 곱한 값

print(x / y) # 해당 요소들끼리 나눗셈
print(np.divide(x, y)) # x와 y를 나눈 값

print(x**3) # 해당 요소들의 지수승
print(np.power(x, 3)) #

print(np.sqrt(x)) # 해당 요소들의 제곱근

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1.  8.]
 [27. 64.]]
[[ 1.  8.]
 [27. 64.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [15]:
x = np.array([[1,2], [3,4]]) # 2 by 2 행렬
y = np.array([[5,6], [7,8]]) # 2 by 2 행렬
print(x)
print(y)

v = np.array([9, 10]) # (2, )벡터 (1-dimensional array)
w = np.array([11, 12]) # (2, )벡터 (1-dimensional array)
print(v, w)

# 벡터와 벡터의 곱
print(v.dot(w)) # v와 w의 dot product = (9 * 11 + 10 * 12)
print(np.dot(v, w))

# 벡터와 행렬의 곱
print(x.dot(v)) # x와 v의 dot product = [(1*9 + 2*10), (3*9 + 4*10)]
print(np.dot(x, v))

# 행렬 행렬의 곱
print(x.dot(y)) # x와 y의 dot product = [[(1*5 + 2*7), (1*6 + 2*8)], [(3*5 + 4*7), (3*6 + 4*8)]]
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10] [11 12]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [16]:
X = np.array([[1,2], [3,4]])
print(np.sum(X)) # 모든 요소를 더한 값 (1 + 2 + 3 + 4)
print(np.sum(X, axis=0)) # 행 (0번째) 방향으로 더하기
print(np.sum(X, axis= 1)) # 열 (1번째) 방향으로 더하기

10
[4 6]
[3 7]


In [17]:
X = np.array([[1,1], [2,2]]) # 행렬
print(X)
print(X.T) # 행과 열의 값이 뒤바뀜

v = np.array([1,2,3])
print(v) # 1차원 벡터
print(v.T) # 벡터는 transpose 해도 똑같은 하나의 행으로 나타남

[[1 1]
 [2 2]]
[[1 2]
 [1 2]]
[1 2 3]
[1 2 3]
