In [6]:
import numpy as np

a = np.array([1,2,3])
print(a, type(a))
print(a.shape)

print(a[0], a[1], a[2])

a[0] = 100
print(a)

b = np.array([[1,2,3], [4,5,6]])
print(b, b.shape)
print(b[0,0], b[1,1], b[0,2])

[1 2 3] <class 'numpy.ndarray'>
(3,)
1 2 3
[100   2   3]
[[1 2 3]
 [4 5 6]] (2, 3)
1 5 3


In [14]:
a = np.zeros((2,3))
print(a)
b = np.ones((4,3))
print(b)
c = np.full((2,2), 7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((3,4))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.51567846 0.67404245 0.83135759 0.37307072]
 [0.1046859  0.28104117 0.06716229 0.48558571]
 [0.99229376 0.38035754 0.37635552 0.93331156]]


In [20]:
a = np.arange(5)
print(a)
b = np.arange(1,3,0.4)
print(b)
c = np.linspace(1., 4., 5)
print(c)

[0 1 2 3 4]
[1.  1.4 1.8 2.2 2.6]
[1.   1.75 2.5  3.25 4.  ]


In [24]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
b = a[:2, 1:3]
print(b)
print(a[0,1])
b[0,0] = 77
print(b)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]
2
[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]]


In [28]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
row_1 = a[1, :]
row_2 = a[1:2, :]
print(row_1, row_1.shape)
print(row_2, row_2.shape)

col_1 = a[:, 1]



col_2 = a[:, 1:2]
print(col_1, col_1.shape)
print(col_2, col_2.shape)

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[2 6] (2,)
[[2]
 [6]] (2, 1)
