In [2]:
import numpy as np

a = np.array([1,2,3])
print(a, type(a))
print(a.shape)

print(a[0], a[1], a[2])

a[0] = 100
print(a)

b = np.array([[1,2,3], [4,5,6]])
print(b, b.shape)
print(b[0,0], b[1,1], b[0,2])

[1 2 3] <class 'numpy.ndarray'>
(3,)
1 2 3
[100   2   3]
[[1 2 3]
 [4 5 6]] (2, 3)
1 5 3


In [3]:
a = np.zeros((2,3))
print(a)
b = np.ones((4,3))
print(b)
c = np.full((2,2), 7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((3,4))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.17209698 0.53720648 0.36459605 0.04583437]
 [0.65913359 0.10701994 0.11217677 0.81874653]
 [0.96156058 0.17000775 0.25072441 0.51263639]]


In [4]:
a = np.arange(5)
print(a)
b = np.arange(1,3,0.4)
print(b)
c = np.linspace(1., 4., 5)
print(c)

[0 1 2 3 4]
[1.  1.4 1.8 2.2 2.6]
[1.   1.75 2.5  3.25 4.  ]


In [5]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
b = a[:2, 1:3]
print(b)
print(a[0,1])
b[0,0] = 77
print(b)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]
2
[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]]


In [6]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
row_1 = a[1, :]
row_2 = a[1:2, :]
print(row_1, row_1.shape)
print(row_2, row_2.shape)

col_1 = a[:, 1]



col_2 = a[:, 1:2]
print(col_1, col_1.shape)
print(col_2, col_2.shape)

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[2 6] (2,)
[[2]
 [6]] (2, 1)


In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

row_r1 = a[1, :] # a의 두 번째 행 (정수 인덱싱)
row_r2 = a[1:2, :] # a의 두 번째 행 (슬라이싱)
print(row_1, row_1.shape) # 정수 인덱싱을 하면 차원이 하나 줄어듦(1차원 배열)
print(row_2, row_2.shape) # 행렬 형태 (2차원 행렬)
print("--*--" * 10)
col_r1 = a[:, 1] # a의 두번째 열 (정수 인덱싱)
col_r2 = a[:, 1:2] # a의 두번째 열 (슬라이싱)
print(col_r1, col_r1.shape) # a의 두 번째 열 (정수 인덱싱)
print(col_r2, col_r2.shape) # a의 두 번째 열 (슬라이싱)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
--*----*----*----*----*----*----*----*----*----*--
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [20]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a[[0,1,2], [0,1,0]]) # 특정한 element를 뽑기
print(np.array([a[0,0], a[1,1], a[2,0]])) # 특정한 element를 뽑아서 배열로 만들어줌
print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [22]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]]) # (4x3)배열
print(a)
b = np.array([0, 2, 0, 1]) # a의 특정한 element 4개를 뽑아낼 때 사용할 index 번호
print(b)
print(a[np.arange(4), b]) # a[0,0], a[1,2], a[2,0], a[3,1])를 뽑아내기

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[ 1  6  7 11]
